<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>896d62cf-6aae-4f56-b89b-5c7a97e414e2</UserSecretsId>
    <StartupObject>CoreNHibernateOracleTest.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentNHibernate" Version="3.1.0" />
    <PackageReference Include="NHibernate" Version="5.3.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.1.2" />
    <PackageReference Include="System.Data.OracleClient" Version="1.0.8" />
  </ItemGroup>


</Project>
